install! 'cocoapods', deterministic_uuids: false,
                      share_schemes_for_development_pods: false

use_frameworks!

platform :ios, '9.0'

target 'Tests' do
  # Our pod.
  pod 'TrackKit', path: '../'

  # The testing pods.
  pod 'Quick',  '~> 1.1'
  pod 'Nimble', '~> 7.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
