source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def common_pods
  pod 'GPXKit', path: '../'
end

target 'Example', exclusive: true do
  common_pods
end

target 'Tests', exclusive: true do
  common_pods

  pod 'Quick',  '~> 0.8.0'
  pod 'Nimble', '~> 3.0.0'
end
