install! 'cocoapods', deterministic_uuids: false,
                      share_schemes_for_development_pods: false

use_frameworks!

platform :ios, '9.0'

target 'Tests' do
  # Our pod.
  pod 'TrackKit', path: '../'

  # The testing pods.
  pod 'Quick',  '~> 1.2'
  pod 'Nimble', '~> 7.0'
end
